### ISSUE TITLE
Flow issues with upgrading to flow-bin 0.38.0 (fbjs-scripts)

### ISSUE THREAD

**Issue by rsolomon** [facebook/fbjs#215]
Using the latest `fbjs-scripts` (`fbjs-scripts@0.7.1`) and `flow-bin@0.38.0`, `partitionObjectByKey.js.flow` throws the following Flow error:

```
/node_modules/fbjs/lib/partitionObjectByKey.js.flow:20
 20:   return partitionObject(source, (_, key) => whitelist.has(key));
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tuple type. This type is incompatible with the expected return type of
 19: function partitionObjectByKey(source: Object, whitelist: Set<string>): Array<Object> {
                                                                            ^^^^^^^^^^^^^ array type
```

**Comment by zpao** [comment]
I just merged #214 and shipped 0.8.9 so you should be good to go.

**Comment by rsolomon** [comment]
@zpao thanks for the update. It looks like the latest `fbjs-scripts` is still `0.7.1` on npm. Would it be possible to push out a version with the fix? Or is it recommended to just use `fbjs` directly?

**Comment by zpao** [comment]
`fbjs` & `fbjs-scripts` are distinct and neither installs the other. `fbjs-scripts` doesn't have any flow files. The error you reported came from `fbjs`, which probably came in as a dependency of something else (React is the usual case). All of those should have `^` deps so a fresh install should get you the updated `fbjs`.

I'd be happy to fix something broken in `fbjs-scripts` but I'm pretty confident that's not the case here.

**Comment by rsolomon** [comment]
Oh jeez, you're totally right. I'm not sure why I thought it was an issue through `fbjs-script`'s dependencies, but you're definitely right.

**Comment by Kadrian** [comment]
This is still an issue in the current react release `15.4.2`, right? I just downgraded to `flow-bin@0.37.4`

**Comment by rsolomon** [comment]
@Kadrian you just need to delete your old React installation. Clearing out `node_modules` entirely and re-installing your dependencies should alleviate the issue.
